### ISSUE TITLE
[NEW TOOL] Tosint (Telegram OSINT) 

### ISSUE THREAD

**Issue by drego85** [cipher387/osint_stuff_tool_collection#2]
Hi cipher387,
I would like to introduce you to my _Tosint (Telegram OSINT_) tool: https://github.com/drego85/tosint

Is a tools to extract information from telegram bots and related associated channels.

I'd love to see it included in this great collection!

**Comment by cipher387** [comment]
Add to Readme instructions on how to get bot token and chat id.

**Comment by cipher387** [comment]
For chat id is possible to use https://codesandbox.io/s/get-telegram-chat-id-q3qkk And how can I find out the token of someone else's chat or channel?

**Comment by drego85** [comment]
You can get them via misconfiguration, exposed backups, exposed git directory, etc!

The tool was mainly created for analyzing tokens/chatid found in phishing kits!

**Comment by cipher387** [comment]
Let's do this then.

You send me in personal messages Token and chat ID for the test. I'll test it today, take screenshots, make a tweet with them, and at the end of the month I'll add it to the collection along with other tools.

**Comment by cipher387** [comment]
Welcome to dm on twitter, telegram, linkedin, discord.

**Comment by drego85** [comment]
Sorry per delay, you have already [tried](https://twitter.com/cyb_detective/status/1472191634377003008) the software yourself.

I close the Issue ;)
