### ISSUE TITLE
Consider adding a free new tool - Hudson Rock cybercrime intelligence tools

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [cipher387/osint_stuff_tool_collection#49]
Free tools that don't require registration and can indicate if a specific digital asset was compromised in a global Infostelaers attack.

Our tools include -

**Domain** - Search for Compromised Corporate & Supply Chain Infrastructure (Discover whether your, or your vendor’s corporate infrastructure has been compromised by Infostealers)

**Email Address** - Search for Compromised Employees, Customers, Users & Partners (Search specific email addresses to find out if your employees, customers, users or partners have been compromised by info-stealing malware)

**Android App** - Search for Compromised Android App Users (Find out whether users of your Android app have had their credentials compromised)

**Technology Profiler** - Discover which Companies are Using a Technology (Citrix, Webmail, Confluence, etc).

**Password Hygiene** - Discover the password hygiene in any company, search any domain to discover if password complexity requirements are implemented based on actual exposed credentials.

They are all available here: https://www.hudsonrock.com/free-tools
Learn more about what Infostealers are: https://www.infostealers.com/

Your consideration of including us on your tool list would be greatly appreciated!

**Comment by C3n7ral051nt4g3ncy** [comment]
Thank you for your great work @hudsonrock-partnerships ! 
Love your tools!
